version: '2'
services:
  db:
    image: mariadb:10.5.8 # mysql:5.7
    ports:
      - "3306:3306"
    command: --init-file /data/application/init.sql
    volumes:
      - ./schema.sql:/data/application/init.sql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: listr_db
  web:
    build: .
    ports:
      - "80:80"
    volumes:
      - ./src:/var/www/html
      - ./php.ini:/usr/local/etc/php/conf.d/30-custom.ini
      - ./apache.conf:/etc/apache2/sites-enabled/000-default.conf
    environment:
      - ALLOW_OVERRIDE=true
    depends_on:
      - db
